### ISSUE TITLE
Bug in plotting with 'typeRose' set to 'default'?

### ISSUE THREAD

**Issue by thomas-nilsson-irfu** [ECheynet/polarPcolor#1]
It appears to me that the optional argument `'typerose'` may have a bug in it (or I may have misunderstood its intended use)..

As a quick example, using your example code:
```matlab
R = linspace(3,10,100);
theta = linspace(0,180,360);
Z = linspace(0,10,360)'*linspace(0,10,100);
figure;
polarPcolor(R,theta,Z,'Ncircles',3, 'typeRose', 'meteo');
```
gives rise to the "default" orientation for your polarPcolor, with zero degrees up towards north, and theta going clockwise around the polar plot to the maximum value of Z directly at the south.. Which is all good, and as expected based on `R`, `theta` and `Z`.

However if one wants to change orientation to have zero deg theta at the east (similar to Matlab's own default value in `polarplot`), then with the following example code:
```matlab
R = linspace(3,10,100);
theta = linspace(0,180,360);
Z = linspace(0,10,360)'*linspace(0,10,100);
figure;
polarPcolor(R,theta,Z,'Ncircles',3, 'typeRose', 'default');
```
we suddenly have shifted only the spokes, ticks etc. and revert orientation of them but the data itself is still plotted with the original orientation and from "north to south" (not "east to west" as the spokes/ticks etc imply).

See example plot:
![polarPcolor_example_typeRose_default](https://user-images.githubusercontent.com/5270200/132472532-dd8ed24d-423b-4aaa-8b65-999ceca8b254.jpg)

As a side note, having "default" as an argument but not having this value be the actual "default" is perhaps making things more confusing than need be.

**Comment by ECheynet** [comment]
Hi Thomas, 

sorry for the very late reply. I have just tested your code and used the most recent version of polarPcolor. It seems it is working reasonably well. I have updated the function polarPcolor since last September, and the bug may have been corrected without me noticing it! 

with the option: 'typeRose', 'meteo'
![test1](https://user-images.githubusercontent.com/13150968/144858762-698c5420-6ac8-4df0-b3c0-f1b411b7b111.png)


with the option: 'typeRose', 'default'

![test2](https://user-images.githubusercontent.com/13150968/144858768-83085d37-c068-418f-9956-f29d7d202b3d.png)
